name: TeaSpoonJP
main: CortexPE\Main
version: 1.2.0
api: 3.9.4
load: STARTUP
author: CortexPE
authors: [xtakumatutix]
description: プラグインでPMMPにバニラ機能を追加
website: https://github.com/CortexPE/TeaSpoon
