name: TeaSpoon
main: CortexPE\Main
version: 1.3.0
api: 3.14.0
load: STARTUP
author: CortexPE
authors: [xtakumatutix]
description: プラグインでPMMPにバニラの要素をちょっと追加します
website: https://github.com/xtakumatutix/TeaSpoonJP
